name: C-1

on:
  push:
    branches: main
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    
    - name: Get submodules hash
      run: echo "hash=$(git submodule status)"
      
    - name: Download and unzip your linux repository of the current commit number of the submodule.
      run: |
        wget https://github.com/min99830/linux/archive/linux-${hash:1:40}.zip
        mkdir linux-${hash:1:40}
        unzip linux-${hash:1:40}.zip -d ./linux-${hash:1:40}
        
    - name: Build the unzipped source code using ./build-linux.sh <unzipped linux dir> tinyconfig
      run: ./build-linux.sh ./${{env.hash}} tinyconfig
