name: C-1

on:
  push:
    tags: csi2115-hw2
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    
    - name: Get hash
      run: echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_HASH
      
    - name: Download and unzip your linux repository of the current commit number of the submodule.
      run: |
        get https://github.com/min99830/linux/archive/${{env.hash}}.zip
        unzip ${{env.hash}}.zip -d ./${{env.hash}}
        
    - name: Build the unzipped source code using ./build-linux.sh <unzipped linux dir> tinyconfig
      run: ./build-linux.sh ./${{env.hash}} tinyconfig
